### ISSUE TITLE
Milestone: Setup kanban board project

### ISSUE THREAD

**Issue by jicamargo** [jicamargo/catalog-of-my-things#20]
## This Issue was created to ask for a review for the first milestone: Setup Kanban board project

You can visit the project [here](https://github.com/jicamargo/catalog-of-my-things/projects/2)

Our team is compound of three members:
  - Team member # 1 ADEYEMI 👉🏽 https://github.com/Emarkees
  - Team member # 2 MOYASI  👉🏽 https://github.com/MoyasiGinko
  - Team member # 3 JORGE   👉🏽 https://github.com/jicamargo

**Comment by Whoistolu** [comment]
Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [REQUIRED] Adeyemi Olusola has 12 points assigned to him, while JORGE CAMARGO has 6 points assigned to him and Moyasi Ginko has 9 points assigned. The requirements state that some students must not have significant (difference >= 5 points) more or less points than others. Let's ensure that the tasks are distributed fairly before you request another review.

- [ ] [REQUIRED] Kindly ensure that the number of points for each card is in the \[Xpt\] prefix as stated. Presently, most of your cards only have numbers in them without the prefix which does not go along with the project recommendation.
### Your Kanban
<img width="354" alt="Screenshot 2023-08-14 at 23 53 07" src="https://github.com/jicamargo/catalog-of-my-things/assets/58692590/326989bd-379f-4e16-b8fe-1397ac6ebbbc">


### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.
### N/A

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jicamargo** [comment]
## ✔️ changes done! Thank you👍🏽

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 ✔️ 

Hi team 👋,

Your kanban board is complete!  There is nothing else to say other than... it's time to start building :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

## Highlights 🎯
✔️ Projects assigned fairly 📌

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
